name: anicross
description: Something I guess

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  #sdk: ">=3.0.0-122.0.dev"

dependencies:
  archive: 
  better_player:
    git:
      url: https://github.com/sha3rawi33/betterplayer/
      ref: new_fixes
  cached_network_image: 
  dio: 
  file_picker: 
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  graphql_flutter: 
  hive: 
  hive_flutter: 
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: linux-video-support
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: linux-video-support
      path: media_kit_video
  media_kit_libs_linux:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: linux-video-support
     path: media_kit_libs_linux
  media_kit_libs_windows_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: linux-video-support
     path: media_kit_libs_windows_video
  path_provider: 
  permission_handler: 
  #preload_page_view: ^0.1.6
  universal_io: 
  xml: 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^2.0.1