name: tokuwari
description: Something I guess

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.1+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliver_tools:
  flutter_html:
  path:
  cached_network_image:
  dio: 
  photo_view:
  flex_color_scheme:
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: media_kit_video
  media_kit_libs_linux:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: libs/linux/media_kit_libs_linux
  media_kit_libs_windows_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: libs/macos/media_kit_libs_macos_video
  media_kit_libs_ios_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: libs/android/media_kit_libs_android_video
  path_provider: 
  window_manager:
  flutter_image:
  encrypt: 
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  expandable_text:
  string_similarity: 
  go_router: 
  # For novels
  archive:
  image:
  html:
  file_picker:
  xml2json:
  permission_handler:
  
dependency_overrides:
  graphql: ^5.2.0-beta.5
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: media_kit

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
dev_dependencies:
  build_runner: 
  flutter_lints: 
  isar_generator: ^3.1.0+1
