name: anicross
description: Something I guess

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  #sdk: ">=3.0.0-122.0.dev"

dependencies:
  archive: 
  better_player:
    git:
      url: https://github.com/femalemonkeyman/betterplayer
      ref: master
  cached_network_image:
  dio: 
  file_picker: 
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: media_kit_video
  media_kit_libs_linux:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: media_kit_libs_linux
  media_kit_libs_windows_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: media_kit_libs_windows_video
  media_kit_libs_macos:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: media_kit_libs_macos
  path_provider: 
  permission_handler: 
  #preload_page_view: ^0.1.6
  universal_io: 
  xml: 
  audio_video_progress_bar: 
  window_manager: 
  graphql:
  material_design_icons_flutter:
  infinite_scroll_pagination:
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  expandable_text: 

dependency_overrides:
  web_socket_channel: 2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: 
  isar_generator: ^3.0.5
