name: anicross
description: Something I guess

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0-290.1.beta"

dependencies:
  
  flutter:
    sdk: flutter
  flutter_html:
  archive:
  path:
  image:
  better_player:
    git:
      url: https://github.com/femalemonkeyman/betterplayer
      ref: master
  cached_network_image:
  dio: 
  file_picker: 
  photo_view: 
  media_kit:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/alexmercerind/media_kit.git
      ref: main
      path: media_kit_video
  media_kit_libs_linux:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: media_kit_libs_linux
  media_kit_libs_windows_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: media_kit_libs_macos_video
  media_kit_libs_ios_video:
    git:
     url: https://github.com/alexmercerind/media_kit
     ref: main
     path: media_kit_libs_ios_video
  path_provider: 
  permission_handler: 
  universal_io: 
  xml2json:
  audio_video_progress_bar: 
  window_manager: 
  graphql:
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  expandable_text:
  material_design_icons_flutter:
  string_similarity: 
  
dependency_overrides:
  web_socket_channel: 2.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
dev_dependencies:
  build_runner: 
  flutter_lints: 
  isar_generator: ^3.0.5
