name: tokuwari
description: Something I guess

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.5.5

environment:
  sdk: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  dio: ^5.7.0
  async: ^2.12.0
  graphql: ^5.2.0-beta.9
  flex_color_scheme: 
    git:  
      url: https://github.com/rydmike/flex_color_scheme
      ref: version-8-0-0
# For novels
  epubx: 
    git: 
     url: https://github.com/femalemonkeyman/epubx
    #path: /mnt/Storage/HomeStuff/Documents/epubx
  html: ^0.15.5
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  # Media kit
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  path_provider: ^2.1.5 
  window_manager: ^0.4.3 
  encrypt: ^5.0.3 
  isar:
    hosted: https://pub.isar-community.dev
    version: ^4.0.3
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^4.0.3
  xml: ^6.5.0
  expand_widget: ^3.1.1
  expandable_page_view: ^1.0.17
  string_similarity: ^2.1.1
  go_router: ^14.6.1 
  cached_network_image: ^3.4.1 
  csslib: ^1.0.2

  #Modules
  key:
    path: ../Projects/modules/key
    # git: 
    #  url: https://github.com/femalemonkeyman/key
  
  collection: ^1.19.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
dependency_overrides:
  graphql: ^5.2.0-beta.9
  js: ^0.7.1
  
  screen_brightness: ">=1.0.1"
  
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
dev_dependencies:
  build_runner: ^2.4.13 
  custom_lint: ^0.6.10
  flutter_lints: ^5.0.0 
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
