name: media_kit
description: A complete video & audio library for Flutter & Dart.
homepage: https://github.com/alexmercerind/media_kit
repository: https://github.com/alexmercerind/media_kit
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  meta: ^1.8.0
  path: ^1.8.0
  http: ^0.13.4
  uri_parser: ^1.0.0
  safe_local_storage: ^1.0.0

dev_dependencies:
  lints: ^1.0.0

ffigen:
  name: MPV
  output: bin/generated/libmpv/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  dart-bool: true
