display_name: Tokuwari

icon: assets/Flutter.png

keywords:


generic_name: Tokuwari

actions:
  

categories:
  - X-Anime

startup_notify: true

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
# 
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include: []
